### ISSUE TITLE
Failed to load file arbitrary.lua.

### ISSUE THREAD

**Issue by JoshuaRogetsWithPieAndSauce** [matemat13/MCserver-RaspberryGPIO#2]
When i try to activate the plugin it gives that error. Here is a picture of my files.
![image](https://user-images.githubusercontent.com/65999444/97101528-3ad50a80-16ee-11eb-95a5-98dcb4037cfe.png)
Error: Failed to load file arbitrary.lua
Hardware: RPi 0

**Comment by matemat13** [comment]
However glad I am that you're interested in my little project, I am afraid that the code in this repository is wildly outdated (the repo is from 2015...). The MCserver on which my code relied no longer exists as there is an official Minecraft server for Raspberry Pi from Mojang. Thus, there is no sense in continuing to support this repo. Also I couldn't but notice that you're using Windows... Are you aware that this code was intended for the Raspberry Pi?

**Comment by JoshuaRogetsWithPieAndSauce** [comment]
yes

**Comment by JoshuaRogetsWithPieAndSauce** [comment]
I am using WinSCP to my rpi

**Comment by JoshuaRogetsWithPieAndSauce** [comment]
And can you help me use GPIO with my Cuberite insatllation? I have no experience
